---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "counter-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "counter-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "counter-service.name" . }}
    spec:
      serviceAccountName: {{ include "counter-service.fullname" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: counter-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: COUNTER_FILE
              value: {{ .Values.env.COUNTER_FILE | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: APP_VERSION
              value: {{ .Values.env.APP_VERSION | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.persistence.mountPath }}
            - name: tmp
              mountPath: /tmp
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "counter-service.fullname" . }}-pvc
        - name: tmp
          emptyDir: {}
      {{- end }}
